-- ============================================================================
-- Aura Database - Seed Presets
-- Idempotent: ON CONFLICT DO NOTHING
-- ============================================================================

INSERT INTO public.presets (
    name, slug, description, mode, prompt_template, negative_prompt,
    icon_url, thumbnail_url, is_premium, sort_order, parameters, replicate_model
) VALUES
('Old Money', 'old-money-paris', 'Тихая роскошь в парижском стиле', 'persona',
    'A person in a minimalist chic outfit, sitting at a classic Parisian cafe, beige and cream color palette, soft afternoon sunlight through large cafe windows, elegant atmosphere, blurred background of Haussmann architecture, expensive aesthetic, quiet luxury, natural skin tone, editorial magazine quality',
    'deformed, distorted, bad anatomy, blurry, low quality, plastic skin, over-sharpened',
    'https://storage.supabase.co/preset-icons/old-money.webp',
    'https://storage.supabase.co/preset-icons/old-money-thumb.webp',
    false, 1, '{"guidance_scale": 3.5, "num_inference_steps": 28, "aspect_ratio": "4:5", "ip_adapter_scale": 0.85, "face_preservation_strength": 0.85}'::jsonb,
    'zsxkib/instant-id:6c8f5e3aeb3a15f91c43c6fb31ebdbd06e3957efa38ce89c696edf2a75012f5c'),
('Urban Night', 'urban-night-tokyo', 'Неоновые огни ночного города', 'persona',
    'Night photography in bustling Tokyo street, cinematic neon lighting, reflections of red and blue city lights on wet pavement, high contrast, street style aesthetic, busy metropolitan background with bokeh effects, sharp details on subject, moody cyberpunk atmosphere without actual cyberpunk elements',
    'deformed, distorted, bad anatomy, blurry, cartoon, anime',
    'https://storage.supabase.co/preset-icons/urban-night.webp',
    'https://storage.supabase.co/preset-icons/urban-night-thumb.webp',
    false, 2, '{"guidance_scale": 4.0, "num_inference_steps": 30, "aspect_ratio": "4:5", "ip_adapter_scale": 0.75, "face_preservation_strength": 0.82}'::jsonb,
    'zsxkib/instant-id:6c8f5e3aeb3a15f91c43c6fb31ebdbd06e3957efa38ce89c696edf2a75012f5c'),
('Scandi Minimalist', 'scandi-minimalist', 'Чистый скандинавский интерьер', 'persona',
    'Clean minimalist Scandinavian interior, person in natural linen clothing, bright natural daylight from large window, white walls and light oak wood textures, clean lines, organic aesthetic, soft shadows, airy and fresh atmosphere, high-end lifestyle photography, serene mood',
    'deformed, distorted, bad anatomy, blurry, cluttered, messy',
    'https://storage.supabase.co/preset-icons/scandi.webp',
    'https://storage.supabase.co/preset-icons/scandi-thumb.webp',
    false, 3, '{"guidance_scale": 3.0, "num_inference_steps": 25, "aspect_ratio": "4:5", "ip_adapter_scale": 0.88, "face_preservation_strength": 0.88}'::jsonb,
    'zsxkib/instant-id:6c8f5e3aeb3a15f91c43c6fb31ebdbd06e3957efa38ce89c696edf2a75012f5c'),
('Editorial Vogue', 'editorial-vogue', 'Высокая мода в стиле Vogue', 'persona',
    'High fashion editorial photoshoot, dramatic studio lighting setup, harsh directional light creating deep shadows, stark monochromatic background or bold single color, avant-garde aesthetic, sharp focus on eyes and facial features, grainy film texture, 90s Vogue magazine style, confident pose',
    'deformed, distorted, bad anatomy, blurry, amateur, snapshot',
    'https://storage.supabase.co/preset-icons/vogue.webp',
    'https://storage.supabase.co/preset-icons/vogue-thumb.webp',
    true, 4, '{"guidance_scale": 4.5, "num_inference_steps": 32, "aspect_ratio": "4:5", "ip_adapter_scale": 0.7, "face_preservation_strength": 0.75}'::jsonb,
    'zsxkib/instant-id:6c8f5e3aeb3a15f91c43c6fb31ebdbd06e3957efa38ce89c696edf2a75012f5c'),
('Analog Film 90s', 'analog-film-90s', 'Винтажная пленочная эстетика', 'persona',
    'Vintage 90s film photography aesthetic, shot on Kodak Portra 400, warm natural skin tones, visible film grain texture, soft lens flare from sunlight, nostalgic vibe, authentic candid moment, raw unposed photography, natural imperfections, slightly faded colors, timeless feel',
    'deformed, distorted, bad anatomy, blurry, digital, over-processed',
    'https://storage.supabase.co/preset-icons/analog.webp',
    'https://storage.supabase.co/preset-icons/analog-thumb.webp',
    false, 5, '{"guidance_scale": 3.2, "num_inference_steps": 26, "aspect_ratio": "4:5", "ip_adapter_scale": 0.9, "face_preservation_strength": 0.9}'::jsonb,
    'zsxkib/instant-id:6c8f5e3aeb3a15f91c43c6fb31ebdbd06e3957efa38ce89c696edf2a75012f5c'),
('Corporate LinkedIn', 'corporate-linkedin', 'Профессиональное бизнес-фото', 'persona',
    'Professional corporate headshot, business attire, modern office background, soft professional lighting, confident expression, clean and polished look, LinkedIn profile quality, neutral background',
    'deformed, distorted, bad anatomy, blurry, casual, unprofessional',
    'https://storage.supabase.co/preset-icons/corporate.webp',
    'https://storage.supabase.co/preset-icons/corporate-thumb.webp',
    true, 6, '{"guidance_scale": 3.0, "num_inference_steps": 25, "aspect_ratio": "1:1", "ip_adapter_scale": 0.88, "face_preservation_strength": 0.92}'::jsonb,
    'zsxkib/instant-id:6c8f5e3aeb3a15f91c43c6fb31ebdbd06e3957efa38ce89c696edf2a75012f5c'),
('Luxury Product', 'product-luxury', 'Премиальная предметная съемка', 'object',
    'High-end product photography, luxury item on marble or velvet surface, professional studio lighting setup, clean white or deep black background, perfect reflections, premium aesthetic, sharp focus on product details, commercial photography quality',
    'deformed, blurry, low quality, amateur, cluttered background',
    'https://storage.supabase.co/preset-icons/product-luxury.webp',
    'https://storage.supabase.co/preset-icons/product-luxury-thumb.webp',
    true, 10, '{"guidance_scale": 3.8, "num_inference_steps": 30, "aspect_ratio": "1:1", "controlnet_conditioning_scale": 0.7, "structure_preservation": "canny"}'::jsonb,
    'jagilley/controlnet-canny:aff48af9c68d162388d230a2ab003f68d2638d88307bdaf1c2f1ac95079c9613'),
('Lifestyle Flatlay', 'lifestyle-flatlay', 'Стильный флэтлей для Instagram', 'object',
    'Lifestyle flatlay photography, artfully arranged items on clean surface, natural daylight, aesthetic composition, soft shadows, Instagram-worthy, trendy minimal style',
    'deformed, blurry, messy, cluttered',
    'https://storage.supabase.co/preset-icons/flatlay.webp',
    'https://storage.supabase.co/preset-icons/flatlay-thumb.webp',
    false, 11, '{"guidance_scale": 3.2, "num_inference_steps": 26, "aspect_ratio": "4:5", "controlnet_conditioning_scale": 0.65, "structure_preservation": "depth"}'::jsonb,
    'jagilley/controlnet-canny:aff48af9c68d162388d230a2ab003f68d2638d88307bdaf1c2f1ac95079c9613')
ON CONFLICT (slug) DO NOTHING;
